services:
  server:
    image: messenger.azurecr.io/messenger-server:latest
    ports:
    - "80:8080"
    environment:
    - NODE_ENV=production
    volumes:
    - "${WEBAPP_STORAGE_HOME}/server/db:/home/node/app/db"
  agents:
    image: messenger.azurecr.io/messenger-agents:latest
    environment:
    - NODE_ENV=production