name: Deploy Containerized Services to Azure App Service

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: messenger-containers
  CONTAINER_REGISTRY: messenger.azurecr.io

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v2
      with:
        login-server: ${{ env.CONTAINER_REGISTRY }}
        username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
        password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}

    - name: Build and push main service image
      uses: docker/build-push-action@v6
      with:
        context: ./server
        push: true
        tags: ${{ env.CONTAINER_REGISTRY }}/messenger-server:${{ github.sha }},${{ env.CONTAINER_REGISTRY }}/messenger-server:latest

    - name: Build and push internal service image
      uses: docker/build-push-action@v6
      with:
        context: ./agents
        push: true
        tags: ${{ env.CONTAINER_REGISTRY }}/messenger-agents:${{ github.sha }},${{ env.CONTAINER_REGISTRY }}/messenger-agents:latest